name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: ./my-cargonaut-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-be-${{ hashFiles('my-cargonaut-backend/package-lock.json') }}

      - name: Install dependencies
        run: npm i -f
      - name: Build
        run: npm run build
      - name: Linter
        run: npm run lint:ci
      - name: Prettier
        run: npm run format:ci
      - name: Test
        run: npm test

  frontend:
    needs: backend
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: ./my-cargonaut-frontend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-fe-${{ hashFiles('my-cargonaut-frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Linter
        run: npm run lint:ci
      - name: Prettier
        run: npm run format:ci
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  deploy:
    needs: frontend
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USER}}/my-cargonaut .
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/my-cargonaut
      