name: Backend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: ./my-cargonaut-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-be-${{ hashFiles('my-cargonaut-backend/package-lock.json') }}

      - name: Install dependencies
        run: npm i -f
      - name: Build
        run: npm run build
      - name: Linter
        run: npm run lint:ci
      - name: Prettier
        run: npm run format:ci
      - name: Test
        run: npm test
