version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yep
      MYSQL_DATABASE: mycargonaut
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306
